# This is the workflow name
name: Hello

# runs on a trigger
on:
  workflow_dispatch:

# These are the jobs inside the workflow
jobs:


  # This is the name of the job
  greet:
    # This is a GitHub runner; each job runs on a runner 
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello."

      - name: say hello to username
        run: echo "Hello ${{ github.actor }}"

  details:
    runs-on: ubuntu-latest
    steps:
      - name: What is the version of Python, Docker, etc.
        run: python3 --version && docker --version
